import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans"; // import font
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        // add font to className, also add antialiased and light mode
        <html lang="en" className={`${GeistSans.className} antialiased bg-white`}>
        <body>{children}</body>
        </html>
    );
}
